language: php

sudo: true
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - PHALCON_VERSION="v3.3.x"

git:
  depth: 1

install:
  - composer self-update
  - git clone --depth=1 -q --branch=${PHALCON_VERSION} https://github.com/phalcon/cphalcon.git
  - '(cd cphalcon/build; bash install &>/dev/null && phpenv config-add ../tests/_ci/phalcon.ini &> /dev/null && cd ../..;)'
  - php --ri phalcon
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 7.3

# References
# https://github.com/Codeception/phalcon-demo/blob/master/.travis.yml
