version: '3.5'

services:
  image-builder:
    build: ./
    image: talentify/phalcon-psr-adapter:latest
  app:
    image: talentify/phalcon-psr-adapter:latest
    volumes:
      - "./:/var/www"
    environment:
      PHP_IDE_CONFIG: "serverName=tflux.me"
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=host.docker.internal"
    extra_hosts:
      - "test.tflux.me:127.0.0.1"
    restart: unless-stopped
