<?php

declare(strict_types=1);

return [
    'HTTP_HOST'                      => 'dev.tfy',
    'HTTP_USER_AGENT'                => 'Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0',
    'HTTP_ACCEPT'                    => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'HTTP_ACCEPT_LANGUAGE'           => 'pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3',
    'HTTP_ACCEPT_ENCODING'           => 'gzip, deflate',
    'HTTP_CONNECTION'                => 'keep-alive',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_PRAGMA'                    => 'no-cache',
    'HTTP_CACHE_CONTROL'             => 'no-cache',
    'PATH'                           => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'SERVER_SIGNATURE'               => '<address>Apache/2.4.25 (Debian) Server at foo.bar Port 80</address>',
    'SERVER_SOFTWARE'                => 'Apache/2.4.25 (Debian)',
    'SERVER_NAME'                    => 'dev.tfy',
    'SERVER_ADDR'                    => '172.20.0.2',
    'SERVER_PORT'                    => '80',
    'REMOTE_ADDR'                    => '172.20.0.1',
    'DOCUMENT_ROOT'                  => '/var/www/html',
    'REQUEST_SCHEME'                 => 'http',
    'CONTEXT_PREFIX'                 => '',
    'CONTEXT_DOCUMENT_ROOT'          => '/var/www/html',
    'SERVER_ADMIN'                   => 'webmaster@localhost',
    'SCRIPT_FILENAME'                => '/var/www/html/index.php',
    'REMOTE_PORT'                    => '53424',
    'GATEWAY_INTERFACE'              => 'CGI/1.1',
    'SERVER_PROTOCOL'                => 'HTTP/1.1',
    'REQUEST_METHOD'                 => 'GET',
    'QUERY_STRING'                   => '',
    'REQUEST_URI'                    => '/',
    'SCRIPT_NAME'                    => '/index.php',
    'PHP_SELF'                       => '/index.php',
    'REQUEST_TIME_FLOAT'             => 1545081131.967,
    'REQUEST_TIME'                   => 1545081131,
    'argv'                           => [],
    'argc'                           => 0,
];
